version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: expense_tracker_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - expense_tracker_network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: expense_tracker_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - expense_tracker_network

  app:
    build: 
      context: .
      dockerfile: src/PFE.ExpenseTracker.API/Dockerfile
    container_name: expense_tracker_app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ExpenseTracker;User=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;Encrypt=False;
      - ConnectionStrings__Redis=redis:6379
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
      - redis
    networks:
      - expense_tracker_network

networks:
  expense_tracker_network:
    driver: bridge

volumes:
  sqlserver_data:
  redis_data:
