version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: expense_tracker_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - expense_tracker_network

  app:
    build: .
    container_name: expense_tracker_app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ExpenseTracker;User=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;Encrypt=False;
    ports:
      - "5000:80"
      - "8080:8080"
    depends_on:
      - sqlserver
    networks:
      - expense_tracker_network
volumes:
  sqlserver_data:
    driver: local

networks:
  expense_tracker_network:
    driver: bridge
